development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: my_app_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: my_app_production
