services:
  backend:
    build:
      context: ./backend
    container_name: rails-backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV:-development}
    env_file:
      - ./backend/.env.${APP_ENV:-development}
    expose:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "8000:3000"
    depends_on:
      - backend
    environment:
      - APP_ENV=${APP_ENV:-development}
    env_file:
      - ./frontend/.env.${APP_ENV:-development}
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_development
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-db: